points_of_interest:
- name: MachineC
  description: A point of interest.
  type: Machine
  position:
    x: -29.3
    y: 17.85
    z: 0.55
  simplified_boundary:
    min:
      x: -29.8
      y: 18.35
      z: -0.45
    max:
      x: -28.8
      y: 17.35
      z: 1.55
- name: House6
  description: A point of interest.
  type: Buildings
  position:
    x: -0.9000015
    y: 3.4
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_x
    point:
      x: 10.44281
      y: 11.61006
      z: 2.5
  simplified_boundary:
    min:
      x: -4.470532
      y: 9.110056
      z: -0.1500001
    max:
      x: 25.35616
      y: -6.093409
      z: 8.651436
- name: MachineB
  description: A point of interest.
  type: Machine
  position:
    x: -37.72
    y: 10.58
    z: 0.55
  simplified_boundary:
    min:
      x: -38.22
      y: 11.08
      z: -0.45
    max:
      x: -37.22
      y: 10.08
      z: 1.55
- name: House4
  description: A point of interest.
  type: Buildings
  position:
    x: -37.2
    y: -38.35266
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_x
    point:
      x: -25.85718
      y: -30.1426
      z: 2.5
  simplified_boundary:
    min:
      x: -40.77053
      y: -32.6426
      z: -0.1500001
    max:
      x: -10.94384
      y: -47.84607
      z: 8.651436
- name: House14
  description: A point of interest.
  type: Buildings
  position:
    x: 46.71346
    y: 20.50236
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_z
    point:
      x: 37.93473
      y: 13.5817
      z: 2.5
  simplified_boundary:
    min:
      x: 40.43473
      y: 22.58274
      z: -0.2824993
    max:
      x: 53.22795
      y: 4.580666
      z: 20.16336
- name: Church
  description: There is a church
  type: Buildings
  position:
    x: 47.81728
    y: -26.95266
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_z
    point:
      x: 33.09906
      y: -31.89515
      z: 2.5
  simplified_boundary:
    min:
      x: 35.59906
      y: -16.84855
      z: -1.144409E-05
    max:
      x: 52.18036
      y: -46.94176
      z: 21.50002
- name: House13
  description: A point of interest.
  type: Buildings
  position:
    x: -20.98655
    y: 16.60236
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_x
    point:
      x: -20.86866
      y: 21.18274
      z: 2.5
  simplified_boundary:
    min:
      x: -27.26527
      y: 18.68274
      z: -0.2825012
    max:
      x: -14.47205
      y: 0.6806679
      z: 20.16336
- name: House12
  description: A point of interest.
  type: Buildings
  position:
    x: -21
    y: -15.4
    z: 0
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: -20.91776
      y: -19.94836
      z: 2.5
  simplified_boundary:
    min:
      x: -27.26903
      y: 0.490715
      z: -0.2825012
    max:
      x: -14.56649
      y: -17.44836
      z: 12.5068
- name: MachineA
  description: A point of interest.
  type: Machine
  position:
    x: -41.9
    y: 21.91
    z: 0.55
- name: House8
  description: A point of interest.
  type: Buildings
  position:
    x: 9.397285
    y: -12.56266
    z: 0
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: 16.31886
      y: -21.31813
      z: 2.5
  simplified_boundary:
    min:
      x: 7.392836
      y: -6.240288
      z: -0.2824974
    max:
      x: 25.24488
      y: -18.81813
      z: 20.16336
- name: House3
  description: A point of interest.
  type: Buildings
  position:
    x: -30.7
    y: 39.1
    z: 0
  simplified_boundary:
    min:
      x: -32.85402
      y: 45.80066
      z: -0.2824974
    max:
      x: -14.70845
      y: 32.79953
      z: 20.16336
- name: House2
  description: A point of interest.
  type: Bulidings
  position:
    x: 3.000004
    y: 39.5
    z: 0
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: -3.921658
      y: 29.75399
      z: 2.5
  simplified_boundary:
    min:
      x: -12.8176
      y: 45.74601
      z: -0.2824993
    max:
      x: 4.974287
      y: 33.25399
      z: 12.5068
- name: Wall(4)
  description: A point of interest.
  type: Wall
  position:
    x: 53.8
    y: 1.200001
    z: 4
  simplified_boundary:
    min:
      x: 52.92552
      y: 49.86245
      z: -0.5831625
    max:
      x: 54.67449
      y: -47.46244
      z: 8.583162
- name: House9
  description: A point of interest.
  type: Buildings
  position:
    x: 0
    y: 14.5
    z: 1.7
  candidate_interaction_points:
  - name: best_approach_neg_x
    point:
      x: -0.9433608
      y: 22.49963
      z: 2.5
  simplified_boundary:
    min:
      x: -6.745056
      y: 19.99963
      z: -0.4656849
    max:
      x: 4.858334
      y: 9.148951
      z: 14.53601
- name: House5
  description: A point of interest.
  type: Buildings
  position:
    x: 2
    y: -37.49266
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_x
    point:
      x: 13.34281
      y: -29.2826
      z: 2.5
  simplified_boundary:
    min:
      x: -1.570531
      y: -31.7826
      z: -1.907349E-06
    max:
      x: 28.25616
      y: -46.98607
      z: 8.651438
- name: House7
  description: A point of interest.
  type: Buildings
  position:
    x: 8.399998
    y: 39.3
    z: 0
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: 15.31876
      y: 29.49954
      z: 2.5
  simplified_boundary:
    min:
      x: 6.245975
      y: 46.00066
      z: -0.2824974
    max:
      x: 24.39155
      y: 32.99954
      z: 20.16336
- name: House15
  description: A point of interest.
  type: Buildings
  position:
    x: 46.7
    y: -11.5
    z: 0
  candidate_interaction_points:
  - name: best_approach_neg_z
    point:
      x: 37.93097
      y: -4.578827
      z: 2.5
  simplified_boundary:
    min:
      x: 40.43097
      y: 4.39071
      z: -0.2825003
    max:
      x: 53.1335
      y: -13.54836
      z: 12.5068
- name: Wall(1)
  description: A point of interest.
  type: Wall
  position:
    x: -45.7
    y: -10.46739
    z: 4
  simplified_boundary:
    min:
      x: -46.2
      y: 29.88371
      z: -0.5831625
    max:
      x: -45.2
      y: -50.81849
      z: 8.583162
- name: Wall(5)
  description: A point of interest.
  type: Wall
  position:
    x: 4.496284
    y: 48.7326
    z: 4
  simplified_boundary:
    min:
      x: -45.47454
      y: 49.60312
      z: -0.5831623
    max:
      x: 54.46711
      y: 47.86209
      z: 8.583162
- name: House10
  description: A point of interest.
  type: Buildings
  position:
    x: -40.17271
    y: -9.552654
    z: 1.7
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: -41.11607
      y: -17.4037
      z: 2.5
  simplified_boundary:
    min:
      x: -46.91777
      y: -4.05303
      z: -0.4656849
    max:
      x: -35.31438
      y: -14.9037
      z: 14.53601
- name: Wall(3)
  description: A point of interest.
  type: Wall
  position:
    x: 2.400002
    y: -51.59999
    z: 4
  simplified_boundary:
    min:
      x: -45.07955
      y: -51.08664
      z: -0.5831633
    max:
      x: 49.87955
      y: -52.11335
      z: 8.583163
- name: Wall(2)
  description: A point of interest.
  type: Wall
  position:
    x: -45.7
    y: 39.75261
    z: 4
  simplified_boundary:
    min:
      x: -46.2
      y: 49.60447
      z: -0.5831625
    max:
      x: -45.2
      y: 29.90075
      z: 8.583162
- name: V_UAV_0
  description: My UAV
  type: UAV
  position:
    x: -42.77
    y: 29.6
    z: 0.1
  simplified_boundary:
    min:
      x: -43.77
      y: 30.475
      z: -0.4
    max:
      x: -41.77
      y: 28.725
      z: 0.6
- name: Ground
  description: This is the floor. During flight, be careful not to collide with the bottom surface. When landing, be careful to determine the distance from the ground
  type: Ground
  position:
    x: 2.9989
    y: -1
    z: -0.5
  simplified_boundary:
    min:
      x: -47.0011
      y: 49
      z: -0.5
    max:
      x: 52.9989
      y: -51
      z: -0.5
- name: House1
  description: There is a house.
  type: Buildings
  position:
    x: 43.2
    y: 39.7
    z: 0
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: 36.27834
      y: 29.954
      z: 2.5
  simplified_boundary:
    min:
      x: 27.38239
      y: 45.94601
      z: -0.2824974
    max:
      x: 45.17428
      y: 33.454
      z: 12.5068
- name: House11
  description: A point of interest.
  type: Buildings
  position:
    x: -38.28271
    y: 38.14735
    z: 1.7
  candidate_interaction_points:
  - name: best_approach_pos_x
    point:
      x: -39.22607
      y: 29.2963
      z: 2.5
  simplified_boundary:
    min:
      x: -45.02777
      y: 43.64697
      z: -0.4656849
    max:
      x: -33.42438
      y: 32.7963
      z: 14.53601
